# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Arty-Z7-20-Master.xdc

# IP: ip/bram_out/bram_out.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_out || ORIG_REF_NAME==bram_out} -quiet] -quiet

# IP: ip/bram_in/bram_in.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_in || ORIG_REF_NAME==bram_in} -quiet] -quiet
